### PR TITLE
Organize needs with their proposed solutions and precedents in a table

### PR DESCRIPTION
**Pull request by Avaq**
# :information_source: [Moved to the Wiki](https://github.com/js-choi/proposal-function-helpers/wiki/FP-Use-Cases)

The information in this pull request has been [moved to a Wiki page](https://github.com/js-choi/proposal-function-helpers/wiki/FP-Use-Cases).

----

I worked on a table to address #2, to somewhat address #3, to illustrate why I opened #5, and to show where this proposal leaves "holes" if the problem space would be viewed as a matrix. I decided to add it via a pull request (without intent for it being merged) so that it would be easier to organize feedback and collaborate to flesh it out.

See [the rendered document](https://github.com/Avaq/proposal-function-helpers/blob/avaq/problem-solution-matrix/problem-solution-matrix.md) here.

### CODE REVIEW

**Comment by js-choi** [comment]
Thanks for working on this. I appreciate the thorough review of precedents from other libraries/languages. 

Although my off-work time is kind of limited right now, I will definitely integrate those precedents into the explainer’s existing precedent tables.

As for the problem–solution matrix itself…perhaps it might belong more in the wiki, since it will probably continue to undergo rapid editing. What do you think?

**Comment by Avaq** [comment]
> perhaps it might belong more in the wiki [...] What do you think?

I think the wiki is an excellent place for it to live, and I'd be happy to move it there. I didn't really know where it would go when I started, nor what kind of feedback I'd get, so I opened a PR to open the possibility for line-by-line feedback.

**Comment by Avaq** [comment]
Currently when I try to access the wiki, I'm redirected to the repo main page. Let me know when and how I can and should move this info to the wiki. From many of the new issues opened, it seems like we could benefit a lot from this information being easily discoverable.

**Comment by js-choi** [comment]
I’ve created a [wiki page](https://github.com/js-choi/proposal-function-helpers/wiki/FP-Use-Cases) that you can edit freely.

**Comment by Avaq** [comment]
@js-choi I'm not sure I actually *can* edit the wiki page; I don't see the edit button. I think you might need to change something in the repo settings.

**Comment by js-choi** [comment]
@Avaq: Sorry, I just changed the setting. You should be good to edit now.

**Pull request closed without merging**
